---
- name: Check for newrelic_license_key
  fail:
    msg: "newrelic_license_key has not been defined"
  when: newrelic_license_key|default(False) == False

- name: Check for newrelic_appname
  fail:
    msg: "newrelic_appname has not been defined"
  when: newrelic_appname|default(False) == False

- include: debian.yml
  when: ansible_os_family == 'Debian'

- include: default.yml
  when: newrelic_loaded_os_family|default(False) == False

- name: Configure New Relic PHP Agent
  template:
    src: newrelic.ini.j2
    dest: /etc/php/{{ php_version }}/mods-available/newrelic.ini
    group: root
    owner: root
    mode: 0644
  when: newrelic_loaded_os_family|default(False) != False

- name: Run New Relic Installer
  shell: NR_INSTALL_SILENT=true newrelic-install install
  when: newrelic_php5_installed.changed

- name: Remove default newrelic.ini config file from cli
  file: dest=/etc/php/{{ php_version }}/cli/conf.d/newrelic.ini state=absent

- name: Remove default newrelic.ini config file form fpm
  file: dest=/etc/php/{{ php_version }}/fpm/conf.d/newrelic.ini state=absent

- name: Activate PHP New Relic Extension
  shell: phpenmod newrelic
