---
- hosts: api
  vars_files:
  vars:
    docroot: /var/www/api.your-website.com/
    app_path: api.your-website.com
    newrelic_appname: api.your-website.com
    app_environment: production
    app_folder_owner: www-data
    app_folder_group: www-data
    php_version: 7.2
    h5bp_config_file: api.conf
    domains_list:
      - { domain: 'api.your-website.com', nginx_template: 'default.conf', domain_alias: ''}
  roles:
    - apt
    - locale
    - codedeploy-agent
    - ntp
    - unzip
    - nginx
    - nginx-sites-configs
    - aws-cli
    - php
    - php.newrelic
  # - default-site //for initial setup only
    - restart.webserver