---
- name: Create logs folder
  file: dest={{ docroot }}logs state=directory

- name: Create supervisor config folder
  file: dest=/etc/supervisor/conf.d state=directory

- name: Copy supervisor service file
  template: src=supervisord.service.j2 dest=/etc/systemd/system/supervisord.service

- name: Copy supervisor config file
  template: src=supervisord.conf.j2 dest=/etc/supervisor/supervisord.conf

- name: Copy worker configuration
  template: src=horizon.conf.j2 dest=/etc/supervisor/conf.d/horizon.conf

- name: Launch service
  systemd: name=supervisord.service state=started

- name: Add the horizon to supervisor
  supervisorctl: name="horizon" state="present"